travis:
  secure:
    BINSTAR_TOKEN: DEJslJPBgy2N97lLaRd/xONy+Zid+ptOEEYmR2xyAKhXJNstgdjTAC2e2JoCTZPVinnUAnrbLPN4zJzwSoYCLmF5bH3sN0rDOdEzQ6Vrkt3Xli7vu5Dnqgsdcd3NlgoxT+RnN0bJ5NJb0tYieTgZa0zuQrTmIHzN2I/7Sp0zkA0yE12q96mRkKs/QxVu/tVK404hGb6h8cXb0tPwChgGteIXEdLhwl6TpAWgEmiPojYtYMZGi0IWbU47sR8D5kf/8ca+Q4lGMGtlP2wyZ9qXGGiycWIOFfGbKBO4YKrZ5vrheEPDbUZ6yFW2D5aUnFaUDid2q1H1JZBpPdoou411BvetiJ8BJqChKQ41TUDTAC6SmEInDmpLtKMuqZoDoU+KgUdDTGYUZP/NvlIFn9ZjFNFMzv48TmhGYKpDwXSG+A0OqkoGzEaAKRsnVriSGb+SyS6+qoazxnlUflYD1J90z56qnIGjlsGLCeLrTxwlLX+OWT/C5hxpeKPlCrdPDqBWwe81bUuI9Gdj+EMsqVeWv/XKPjblGWB59ABsjJVlxGSFeZiPebQECyCYRiMC74DxSpdEFDHVf574rBNAxEW5eNmeGxmU5qRTSkm5T+HmKkJJM6I6rm6EpDBJws5ifBq2adr5QiK8aHlrtEEzU8Klxhv4IsmYJJfBUom96nj+EWY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
